import { Inter } from "next/font/google";
import "../../globals.css";
import SideBar from "@/components/dashboard/SideBar";
import { DashboardProvider } from "@/context/ContextDashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DashboardProvider>
      <html lang="en">
        <body className={inter.className}>
          <SideBar />
          {children}
        </body>
      </html>
    </DashboardProvider>
  );
}
