import { Inter } from "next/font/google";
import "../../globals.css";
import SideBar from "@/components/dashboard/SideBar";
import { DashboardProvider } from "@/context/ContextDashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DashboardProvider>
      <html lang="en">
      <body className="bg-zinc-100 dark:bg-zinc-950 text-zinc-400 ">
          <SideBar />
          <main className=" pt-20 px-4  md:pr-8 md:pl-64  ">{children}</main>
        </body>
      </html>
    </DashboardProvider>
  );
}
